export const reports = [
  {
    id: 1,
    title: "Storföretagens historiska utsläpp",
    slug: "storföretagens-historiska-utsläpp",
    date: "2025-03-11",
    excerpt: "En analys av 150 bolags klimatredovisningar",
    readTime: "15 min",
    category: "Rapport",
    author: {
      name: "Alexandra Palmquist",
      avatar: "/people/alex.jpg",
    },
    pdfUrl: "/reports/2025-03-17_StorfoeretagensHistoriskaUtslaepp.pdf",
    coverImage: "/images/reportImages/2024_report_sv2.png",
    language: "sv",
  },
  {
    id: 2,
    title: "Bolagsklimatkollen",
    slug: "bolags-klimatkollen",
    date: "2024-06-01",
    excerpt: "En analys av 150 svenska storbolags klimatredovisning 2023",
    readTime: "15 min",
    category: "Rapport",
    author: {
      name: "Alexandra Palmquist",
      avatar: "/people/alex.jpg",
    },
    pdfUrl: "/reports/2024-06-Bolagsklimatkollen.pdf",
    coverImage: "/images/reportImages/2023_bolagsklimatkollen2.png",
    language: "sv",
  },
  {
    id: 3,
    title: "Corporate Climate Checker",
    slug: "corporate-climate-checker",
    date: "2024-08-01",
    excerpt:
      "An analysis of 150 major Swedish companies' climate reporting 2023",
    readTime: "15 min",
    category: "Report",
    author: {
      name: "Alexandra Palmquist",
      avatar: "/people/alex.jpg",
    },
    pdfUrl: "/reports/2024-08_CorporateClimateChecker.pdf",
    coverImage: "/images/reportImages/2023_corportateclimatechecker2.png",
    language: "en",
  },
  {
    id: 3,
    title: "Typology of Data Quality Problems in the Corporate Reporting of GHG Emissions",
    slug: "typology-of-data-quality-problems-in-corporate-reporting-of-ghg-emissions",
    date: "2025-05-26",
    excerpt:
      "A typology of data quality problems in corporate reporting of GHG emissions. A report by Green Data, Indicators, Algorithms (Green DIA), funded by the Bavarian Research Institute for Digital Transformation (bidt) and Klimatkollen.",
    readTime: "15 min",
    category: "Report",
    author: {
      name: "Green DIA",
    },
    pdfUrl: "/reports/Typology_of_Data_Quality_Problems_in_Corporate_Reporting.docx.pdf",
    coverImage: "/images/reportImages/typology-of-errors.png",
    language: "en",
  },
];
